name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  stable:
    name: Rust Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo test
